"""empty message

Revision ID: 3ed8d1830a22
Revises: bae95a98d4ad
Create Date: 2020-08-03 15:15:06.874452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ed8d1830a22'
down_revision = 'bae95a98d4ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('fk_rounds_room_id_rooms'), 'rounds', 'rooms', ['room_id'], ['room_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_rounds_room_id_rooms'), 'rounds', type_='foreignkey')
    # ### end Alembic commands ###
