"""empty message

Revision ID: 687963e1f1d4
Revises: df9cb966820b
Create Date: 2020-07-12 21:50:57.175079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '687963e1f1d4'
down_revision = 'df9cb966820b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('game_reset_votes', sa.Integer(), nullable=False, default=0))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rooms', 'game_reset_votes')
    # ### end Alembic commands ###
