"""empty message

Revision ID: 6c793ad05c03
Revises: 3ed8d1830a22
Create Date: 2020-08-03 20:47:11.130300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c793ad05c03'
down_revision = '3ed8d1830a22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('fk_card_history_round_number_rounds'), 'card_history', 'rounds', ['round_number', 'room_id'], ['round_number', 'room_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_card_history_round_number_rounds'), 'card_history', type_='foreignkey')
    # ### end Alembic commands ###
