"""empty message

Revision ID: 9cfb4a7edd91
Revises: 92755e59dabd
Create Date: 2020-05-10 22:54:13.155481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9cfb4a7edd91'
down_revision = '92755e59dabd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card_history',
    sa.Column('card_played_id', sa.Integer(), nullable=False),
    sa.Column('player_name', sa.String(length=255), nullable=True),
    sa.Column('round_number', sa.Integer(), nullable=True),
    sa.Column('room_id', sa.String(length=255), nullable=True),
    sa.Column('card_played', sa.Text(), nullable=True),
    sa.Column('card_type', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('card_played_id')
    )
    op.create_table('rounds',
    sa.Column('room_id', sa.String(length=255), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.Column('question_card_holder', sa.String(length=255), nullable=True),
    sa.Column('number_of_answer_cards', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('room_id', 'round_number')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rounds')
    op.drop_table('card_history')
    # ### end Alembic commands ###
