"""empty message

Revision ID: bae95a98d4ad
Revises: 687963e1f1d4
Create Date: 2020-08-03 13:19:45.342926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bae95a98d4ad'
down_revision = '687963e1f1d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('fk_persons_current_room_rooms'), 'persons', 'rooms', ['current_room'], ['room_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_persons_current_room_rooms'), 'persons', type_='foreignkey')
    # ### end Alembic commands ###
