"""empty message

Revision ID: cbbbf762e2d2
Revises: 
Create Date: 2020-05-07 21:07:27.374728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbbbf762e2d2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('persons',
    sa.Column('player_name', sa.String(length=255), nullable=False),
    sa.Column('current_room', sa.String(length=255), nullable=False),
    sa.Column('game_points', sa.String(length=255), nullable=True),
    sa.Column('last_active', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('player_name', 'current_room')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('persons')
    # ### end Alembic commands ###
