"""empty message

Revision ID: df9cb966820b
Revises: fe776241a827
Create Date: 2020-07-11 11:24:44.770981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df9cb966820b'
down_revision = 'fe776241a827'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('persons', sa.Column('game_reset_vote', sa.Boolean(), nullable=True, default=False))
    op.add_column('rooms', sa.Column('game_reset_initiated', sa.Boolean(), nullable=True, default=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rooms', 'game_reset_initiated')
    op.drop_column('persons', 'game_reset_vote')
    # ### end Alembic commands ###
