"""empty message

Revision ID: fe776241a827
Revises: 9cfb4a7edd91
Create Date: 2020-06-08 19:20:30.644539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe776241a827'
down_revision = '9cfb4a7edd91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('last_activity_check', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rooms', 'last_activity_check')
    # ### end Alembic commands ###
